apiVersion: v1
kind: Service
metadata:
  name: svc-web-on-premise
spec:
  type: NodePort
  clusterIP: 10.96.20.20
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30100
  selector:
    app: web-on-premise
