apiVersion: apps/v1
kind: Deployment
metadata:
  name: was-on-premise
  annotations:
    kubernetes.io/change-cause: was-on-premise:v1.5
spec:
  replicas: 2
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: was-on-premise
  template:
    metadata:
      labels:
        app: was-on-premise
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - was-on-premise
              topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: was-on-premise
      containers:
      - image: soonge97/was-on-premise:v1.7
        name: was-on-premise
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
            memory: 250Mi
          limits:
            cpu: 250m
            memory: 250Mi
